lib/geonode/geonode/documents/urls.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from .views import DocumentUploadView, DocumentUpdateView

js_info_dict = {
    'packages': ('geonode.documents',),
}

urlpatterns = patterns('geonode.documents.views',
                       url(r'^$', TemplateView.as_view(template_name='documents/document_list.html'),
                           name='document_browse'),
                       url(r'^(?P<docid>\d+)/?$', 'document_detail', name='document_detail'),
                       url(r'^(?P<docid>\d+)/download/?$', 'document_download', name='document_download'),
                       url(r'^(?P<docid>\d+)/replace$', login_required(DocumentUpdateView.as_view()),
                           name="document_replace"),
                       url(r'^(?P<docid>\d+)/remove$', 'document_remove', name="document_remove"),
                       url(r'^upload/?$', login_required(DocumentUploadView.as_view()), name='document_upload'),
                       url(r'^search/?$', 'document_search_page', name='document_search_page'),
                       url(r'^(?P<docid>\d+)/metadata$', 'document_metadata', name='document_metadata'),
                       )

lib/geonode/geonode/documents/models.py
import logging
import os
import uuid
from urlparse import urlparse

from django.db import models
from django.db.models import signals
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.contrib.contenttypes import generic
from django.contrib.staticfiles import finders
from django.utils.translation import ugettext_lazy as _

from geonode.layers.models import Layer
from geonode.base.models import ResourceBase, resourcebase_post_save, Link
from geonode.documents.enumerations import DOCUMENT_TYPE_MAP, DOCUMENT_MIMETYPE_MAP
from geonode.maps.signals import map_changed_signal
from geonode.maps.models import Map
from geonode.security.models import remove_object_permissions

IMGTYPES = ['jpg', 'jpeg', 'tif', 'tiff', 'png', 'gif']

logger = logging.getLogger(__name__)


class Document(ResourceBase):

    """
    A document is any kind of information that can be attached to a map such as pdf, images, videos, xls...
    """

    # Relation to the resource model
    content_type = models.ForeignKey(ContentType, blank=True, null=True)
    object_id = models.PositiveIntegerField(blank=True, null=True)
    resource = generic.GenericForeignKey('content_type', 'object_id')

    doc_file = models.FileField(upload_to='documents',
                                null=True,
                                blank=True,
                                verbose_name=_('File'))

    extension = models.CharField(max_length=128, blank=True, null=True)

    doc_type = models.CharField(max_length=128, blank=True, null=True)

    doc_url = models.URLField(
        blank=True,
        null=True,
        help_text=_('The URL of the document if it is external.'),
        verbose_name=_('URL'))

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('document_detail', args=(self.id,))

    @property
    def name_long(self):
        if not self.title:
            return str(self.id)
        else:
            return '%s (%s)' % (self.title, self.id)

    def _render_thumbnail(self):
        from cStringIO import StringIO

        size = 200, 150

        try:
            from PIL import Image, ImageOps
        except ImportError, e:
            logger.error(
                '%s: Pillow not installed, cannot generate thumbnails.' %
                e)
            return None

        try:
            # if wand is installed, than use it for pdf thumbnailing
            from wand import image
        except:
            wand_available = False
        else:
            wand_available = True

        if wand_available and self.extension and self.extension.lower(
        ) == 'pdf' and self.doc_file:
            logger.debug(
                u'Generating a thumbnail for document: {0}'.format(
                    self.title))
            try:
                with image.Image(filename=self.doc_file.path) as img:
                    img.sample(*size)
                    return img.make_blob('png')
            except:
                logger.debug('Error generating the thumbnail with Wand, cascading to a default image...')
        # if we are still here, we use a default image thumb
        if self.extension and self.extension.lower() in IMGTYPES and self.doc_file:
            img = Image.open(self.doc_file.path)
            img = ImageOps.fit(img, size, Image.ANTIALIAS)
        else:
            filename = finders.find('documents/{0}-placeholder.png'.format(self.extension), False) or \
                finders.find('documents/generic-placeholder.png', False)

            if not filename:
                return None

            img = Image.open(filename)

        imgfile = StringIO()
        img.save(imgfile, format='PNG')
        return imgfile.getvalue()

    @property
    def class_name(self):
        return self.__class__.__name__

    class Meta(ResourceBase.Meta):
        pass


def get_related_documents(resource):
    if isinstance(resource, Layer) or isinstance(resource, Map):
        ct = ContentType.objects.get_for_model(resource)
        return Document.objects.filter(content_type=ct, object_id=resource.pk)
    else:
        return None


def pre_save_document(instance, sender, **kwargs):
    base_name, extension, doc_type = None, None, None

    if instance.doc_file:
        base_name, extension = os.path.splitext(instance.doc_file.name)
        instance.extension = extension[1:]
        doc_type_map = DOCUMENT_TYPE_MAP
        doc_type_map.update(getattr(settings, 'DOCUMENT_TYPE_MAP', {}))
        if doc_type_map is None:
            doc_type = 'other'
        else:
            doc_type = doc_type_map.get(instance.extension, 'other')
        instance.doc_type = doc_type

    elif instance.doc_url:
        if '.' in urlparse(instance.doc_url).path:
            instance.extension = urlparse(instance.doc_url).path.rsplit('.')[-1]

    if not instance.uuid:
        instance.uuid = str(uuid.uuid1())
    instance.csw_type = 'document'

    if instance.abstract == '' or instance.abstract is None:
        instance.abstract = 'No abstract provided'

    if instance.title == '' or instance.title is None:
        instance.title = instance.doc_file.name

    if instance.resource:
        instance.csw_wkt_geometry = instance.resource.geographic_bounding_box.split(
            ';')[-1]
        instance.bbox_x0 = instance.resource.bbox_x0
        instance.bbox_x1 = instance.resource.bbox_x1
        instance.bbox_y0 = instance.resource.bbox_y0
        instance.bbox_y1 = instance.resource.bbox_y1
    else:
        instance.bbox_x0 = -180
        instance.bbox_x1 = 180
        instance.bbox_y0 = -90
        instance.bbox_y1 = 90


def post_save_document(instance, *args, **kwargs):

    name = None
    ext = instance.extension
    mime_type_map = DOCUMENT_MIMETYPE_MAP
    mime_type_map.update(getattr(settings, 'DOCUMENT_MIMETYPE_MAP', {}))
    mime = mime_type_map.get(ext, 'text/plain')
    url = None

    if instance.doc_file:
        name = "Hosted Document"
        url = '%s%s' % (
            settings.SITEURL[:-1],
            reverse('document_download', args=(instance.id,)))
    elif instance.doc_url:
        name = "External Document"
        url = instance.doc_url

    if name and url:
        Link.objects.get_or_create(
            resource=instance.resourcebase_ptr,
            url=url,
            defaults=dict(
                extension=ext,
                name=name,
                mime=mime,
                url=url,
                link_type='data',))


def create_thumbnail(sender, instance, created, **kwargs):
    from geonode.tasks.update import create_document_thumbnail

    create_document_thumbnail.delay(object_id=instance.id)


def update_documents_extent(sender, **kwargs):
    model = 'map' if isinstance(sender, Map) else 'layer'
    ctype = ContentType.objects.get(model=model)
    for document in Document.objects.filter(content_type=ctype, object_id=sender.id):
        document.save()


def pre_delete_document(instance, sender, **kwargs):
    remove_object_permissions(instance.get_self_resource())


signals.pre_save.connect(pre_save_document, sender=Document)
signals.post_save.connect(create_thumbnail, sender=Document)
signals.post_save.connect(post_save_document, sender=Document)
signals.post_save.connect(resourcebase_post_save, sender=Document)
signals.pre_delete.connect(pre_delete_document, sender=Document)
map_changed_signal.connect(update_documents_extent)

lib/geonode/geonode/documents/forms.py
import json
import os
import re
import autocomplete_light

from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from django.conf import settings
from django.forms import HiddenInput, TextInput
from modeltranslation.forms import TranslationModelForm

from geonode.documents.models import Document
from geonode.maps.models import Map
from geonode.layers.models import Layer

autocomplete_light.autodiscover() # flake8: noqa

from geonode.base.forms import ResourceBaseForm


class DocumentForm(ResourceBaseForm):

    resource = forms.ChoiceField(label='Link to')

    def __init__(self, *args, **kwargs):
        super(DocumentForm, self).__init__(*args, **kwargs)
        rbases = list(Layer.objects.all())
        rbases += list(Map.objects.all())
        rbases.sort(key=lambda x: x.title)
        rbases_choices = []
        rbases_choices.append(['no_link', '---------'])
        for obj in rbases:
            type_id = ContentType.objects.get_for_model(obj.__class__).id
            obj_id = obj.id
            form_value = "type:%s-id:%s" % (type_id, obj_id)
            display_text = '%s (%s)' % (obj.title, obj.polymorphic_ctype.model)
            rbases_choices.append([form_value, display_text])
        self.fields['resource'].choices = rbases_choices
        if self.instance.content_type:
            self.fields['resource'].initial = 'type:%s-id:%s' % (
                self.instance.content_type.id, self.instance.object_id)

    def save(self, *args, **kwargs):
        contenttype_id = None
        contenttype = None
        object_id = None
        resource = self.cleaned_data['resource']
        if resource != 'no_link':
            matches = re.match("type:(\d+)-id:(\d+)", resource).groups()
            contenttype_id = matches[0]
            object_id = matches[1]
            contenttype = ContentType.objects.get(id=contenttype_id)
        self.cleaned_data['content_type'] = contenttype_id
        self.cleaned_data['object_id'] = object_id
        self.instance.object_id = object_id
        self.instance.content_type = contenttype
        return super(DocumentForm, self).save(*args, **kwargs)

    class Meta(ResourceBaseForm.Meta):
        model = Document
        exclude = ResourceBaseForm.Meta.exclude + (
            'content_type',
            'object_id',
            'doc_file',
            'extension',
            'doc_type',
            'doc_url')


class DocumentDescriptionForm(forms.Form):
    title = forms.CharField(300)
    abstract = forms.CharField(1000, widget=forms.Textarea, required=False)
    keywords = forms.CharField(500, required=False)


class DocumentReplaceForm(forms.ModelForm):

    """
    The form used to replace a document.
    """

    class Meta:
        model = Document
        fields = ['doc_file', 'doc_url']

    def clean(self):
        """
        Ensures the doc_file or the doc_url field is populated.
        """
        cleaned_data = super(DocumentReplaceForm, self).clean()
        doc_file = self.cleaned_data.get('doc_file')
        doc_url = self.cleaned_data.get('doc_url')

        if not doc_file and not doc_url:
            raise forms.ValidationError(_("Document must be a file or url."))

        if doc_file and doc_url:
            raise forms.ValidationError(
                _("A document cannot have both a file and a url."))

        return cleaned_data

    def clean_doc_file(self):
        """
        Ensures the doc_file is valid.
        """
        doc_file = self.cleaned_data.get('doc_file')

        if doc_file and not os.path.splitext(
                doc_file.name)[1].lower()[
                1:] in settings.ALLOWED_DOCUMENT_TYPES:
            raise forms.ValidationError(_("This file type is not allowed"))

        return doc_file


class DocumentCreateForm(TranslationModelForm):

    """
    The document upload form.
    """
    permissions = forms.CharField(
        widget=HiddenInput(
            attrs={
                'name': 'permissions',
                'id': 'permissions'}),
        required=True)
    resource = forms.CharField(
        required=False,
        label=_("Link to"),
        widget=TextInput(
            attrs={
                'name': 'title__contains',
                'id': 'resource'}))

    class Meta:
        model = Document
        fields = ['title', 'doc_file', 'doc_url']
        widgets = {
            'name': HiddenInput(attrs={'cols': 80, 'rows': 20}),
        }

    def clean_permissions(self):
        """
        Ensures the JSON field is JSON.
        """
        permissions = self.cleaned_data['permissions']

        try:
            return json.loads(permissions)
        except ValueError:
            raise forms.ValidationError(_("Permissions must be valid JSON."))

    def clean(self):
        """
        Ensures the doc_file or the doc_url field is populated.
        """
        cleaned_data = super(DocumentCreateForm, self).clean()
        doc_file = self.cleaned_data.get('doc_file')
        doc_url = self.cleaned_data.get('doc_url')

        if not doc_file and not doc_url:
            raise forms.ValidationError(_("Document must be a file or url."))

        if doc_file and doc_url:
            raise forms.ValidationError(
                _("A document cannot have both a file and a url."))

        return cleaned_data

    def clean_doc_file(self):
        """
        Ensures the doc_file is valid.
        """
        doc_file = self.cleaned_data.get('doc_file')

        if doc_file and not os.path.splitext(
                doc_file.name)[1].lower()[
                1:] in settings.ALLOWED_DOCUMENT_TYPES:
            raise forms.ValidationError(_("This file type is not allowed"))

        return doc_file

lib/geonode/geonode/documents/templates/documents/document_base.html
{% extends "site_base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %} {{ block.super }} {% endblock %}

{% block body_class %}documents{% endblock %}

{% block body_outer %}
{% block body %}{% endblock body %}
{% block sidebar %}{% endblock sidebar %}
{% endblock body_outer %}

lib/geonode/geonode/documents/templates/documents/document_detail.html
{% extends "documents/document_base.html" %}
{% load i18n %}
{% load dialogos_tags %}
{% load agon_ratings_tags %}
{% load bootstrap_tags %}
{% load url from future %}
{% load base_tags %}
{% load guardian_tags %}

{% block title %}{{ resource.title }} — {{ block.super }}{% endblock %}

{% block head %}

  {% if TWITTER_CARD %}
    {% include "base/_resourcebase_twittercard.html" %}
  {% endif %}
  {% if OPENGRAPH_ENABLED %}
    {% include "base/_resourcebase_opengraph.html" %}
  {% endif %}

{{ block.super }}
{% endblock %}

{% block body_class %}documents{% endblock %}

{% block body_outer %}

<div class="page-header">
  <h2>{{ resource.title }}</h2>
</div>

<div class="row">
  <div class="col-md-8">
    {% if "download_resourcebase" in perms_list %}
      {% if resource.extension|lower in imgtypes and resource.doc_file %}
      <div id="embedded_map">
        <a style="text-decoration:none;" href="{% url "document_download" resource.id %}" target="_blank">
          <img src="{% url "document_download" resource.id %}" width='500' class="img-responsive" />
        </a>
      </div>
      {% elif resource.doc_file %}
      <p><a href="{% url "document_download" resource.id %}" target="_blank">Download the {{ resource }} document</a></p>
      {% elif  resource.doc_url %}
      <p><a href="{{ resource.doc_url }}" target="_blank">Download the {{ resource }} document.</a> <small>({% trans 'External Resource' %})</small></p>
      {%  endif %}
    {%  endif %}
       
    <div class="documents-actions">
      {% include "_actions.html" %}
    </div>

    <div class="tab-content">
      {% include "base/resourcebase_info_panel.html" %}

      {% block social_links %}
        {% include "social_links.html" %}
      {% endblock %}
        
      <article id="comments" class="tab-pane">
      {% include "_comments.html" %}
      </article>
        
      <article id="rate" class="tab-pane">
        <!-- TODO: Move this to a reusable template snippet -->
        {% if request.user.is_authenticated %}
        <h4>{% trans "Rate this document" %}</h4>
        {% user_rating request.user resource "document" as user_document_rating %}
        <div id="user_rating" class="category-layer" data-score="{{user_document_rating}}"></div>
        {% endif %}
        <h4>{% trans 'Average Rating' %}</h4>
        {% overall_rating resource "document" as document_rating %}
        {% num_ratings resource as num_votes %}
        <div class="overall_rating" style="float:left" data-score="{{ document_rating }}"></div> ({{num_votes}})
        <!-- TODO: Add display of who gave what rating based -->
      </article>

      {% if EXIF_ENABLED and exif_data %}
        {% with "exif/_exif_document_detail.html" as exif_template %}
            {% include exif_template %}
        {% endwith %}
      {% endif %}
    </div>
  </div>

  <div class="col-md-4">

    <ul class="list-group">
      <li class="list-group-item">
      {% if "download_resourcebase" in perms_list %}
        {% if resource.extension|lower in imgtypes and resource.doc_file %}
          <a style="text-decoration:none;" target="_blank" href="{% url "document_download" resource.id %}"><button class="btn btn-success btn-md btn-block">{% trans "Download Document" %}</button></a>
        {% elif resource.doc_file %}
          <a style="text-decoration:none;" target="_blank" href="{% url "document_download" resource.id %}"><button class="btn btn-success btn-md btn-block">{% trans "Download Document" %}</button></a>
        {% elif  resource.doc_url %}
          <a style="text-decoration:none;" target="_blank" href="{{ resource.doc_url }}"><button class="btn btn-success btn-md btn-block">{% trans "Download Document" %}</button></a>
        {%  endif %}
      {% else %}
        {% if request.user.is_authenticated %}
        <button class="btn btn-success btn-md btn-block" id="request-download">{% trans "Request Download" %}</button>
        {%  endif %}
      {%  endif %}
      </li>

      <li class="list-group-item">
        <button class="btn btn-success btn-md btn-block" data-toggle="modal" data-target="#edit-document">{% trans "Edit Document" %}</button>
      </li>
      <div class="modal fade" id="edit-document" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title" id="myModalLabel">{% trans "Edit Document" %}</h4>
            </div>
            <div class="modal-body">

              <div class="row edit-modal">
                {% if "change_resourcebase_metadata" in perms_list %}
                <div class="col-sm-3">
                  <i class="fa fa-list-alt fa-3x"></i>
                  <h4>{% trans "Metadata" %}</h4>
                  <a class="btn btn-default btn-block btn-xs" href="{% url "document_metadata" resource.id %}">{% trans "Edit" %}</a>
                </div>
                {% endif %}
                {% if "change_resourcebase" in perms_list or "delete_resourcebase" in perms_list %}
                <div class="col-sm-3">
                  <i class="fa fa-file-text-o fa-3x"></i>
                  <h4>{% trans "Document" %}</h4>
                  {% if "change_resourcebase" in perms_list %}
                  <a class="btn btn-default btn-block btn-xs" href="{% url "document_replace" resource.id %}">{% trans "Replace" %}</a>
                  {% endif %}
                  {% if "delete_resourcebase" in perms_list %}
                  <a class="btn btn-danger btn-block btn-xs" href="{% url "document_remove" resource.id %}">{% trans "Remove" %}</a>
                  {% endif %}
                </div>
                {% endif %}
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
            </div>
          </div>
        </div>
      </div>

      <li class="list-group-item">
        <button class="btn btn-default btn-md btn-block" data-toggle="modal" data-target="#download-metadata">{% trans "Download Metadata" %}</button>
      </li>
      <div class="modal fade" id="download-metadata" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title" id="myModalLabel">{% trans "Download Metadata" %}</h4>
            </div>
            <div class="modal-body">
              <ul>
                {% for link in metadata %}
                <li><a href="{{ link.url }}">{{ link.name }}</a></li>
                {% endfor %}
              </ul>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
            </div>
          </div>
        </div>
      </div>

      <li class="list-group-item">
        <h4>{% trans "Resource using this document" %}</h4>
        {% if layer.maps %}
        <p>{% trans "List of resources using this document:" %}</p>
        {% endif %}
        <ul class="list-unstyled">
          {% if related.title %}
          <p>{% trans "This document is related to a " %} {{ resource.content_type.name }}</p>
          <a href='{{ related.get_absolute_url }}'>{{ related.title }}</a>
          {% else %}
          <p>{% trans "This document is not related to any maps or layers" %}</p>
          {% endif %}
        </ul>
      </li>

      {% if "change_resourcebase_permissions" in perms_list %}
      <li class="list-group-item">
        <h4>{% trans "Permissions" %}</h4>
        <p>{% trans "Click the button below to change the permissions of this document." %}</p>
        <p><a href="#modal_perms" data-toggle="modal" class="btn btn-success btn-block" data-target="#_permissions">{% trans "Change Document Permissions" %}</a></p>
      </li>
      {% include "_permissions_form.html" %}
      {% endif %}

      {% include "base/_resourcebase_contact_snippet.html" %}

    </ul>
  </div>
</div>
{% endblock %}

{% block extra_script %}
{% if SOCIAL_BUTTONS %}
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
{% endif %}
    {% if request.user.is_authenticated %}
        {% user_rating_js request.user resource "document" %}
    {% else %}
        {% overall_rating resource "document" as the_doc_rating %}
    {% endif %}
    {% include 'rating.html' %}
    {% include 'request_download.html' %}
    <script type="text/javascript">
        {% if SOCIAL_BUTTONS %}
        (function() {
            var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
            po.src = 'https://apis.google.com/js/plusone.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
        })();
        {% endif %}
    </script>
    {% include "_permissions_form_js.html" %}
{% endblock extra_script %}

lib/geonode/geonode/documents/templates/documents/document_list.html
{% extends "documents/document_base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load url from future %}

{% block title %} {% trans "Explore Documents" %} - {{ block.super }} {% endblock %}

{% block body_class %}documents documents-list explore{% endblock %}

{% block body %}
<div class="page-header">
  <a href="{% url "document_upload" %}" class="btn btn-success pull-right">{% trans "Upload Documents" %}</a>
  <h2>{% trans "Explore Documents" %}</h2>
</div>
  {% with include_type_filter='true' %}
  {% with facet_type='documents' %}
  {% with header='Document Type' %}
  {% with filter='doc_type__in' %}
  {% include "search/_search_content.html" %}
  {% endwith %}
  {% endwith %}
  {% endwith %}
  {% endwith %}
  {% include "_bulk_permissions_form.html" %}
{% endblock %}

{% block extra_script %}
  {% if GEONODE_SECURITY_ENABLED %}
    {% include "_permissions_form_js.html" %}
  {% endif %}
  <script type="text/javascript">
      {% if HAYSTACK_SEARCH %}
          SEARCH_URL = '{% url 'api_get_search' api_name='api' resource_name='documents'%}'
      {% else %}
          SEARCH_URL = '{% url 'api_dispatch_list' api_name='api' resource_name='documents' %}';
      {% endif %}
    FILTER_TYPE = 'document';
  </script>
  {% with include_spatial='true' %}
  {% include 'search/search_scripts.html' %}
  {% endwith %}
{% endblock extra_script %}

lib/geonode/geonode/documents/templates/documents/document_remove.html
{% extends "documents/document_base.html" %}
{% load i18n %}

{% block title %}{% trans "Deleting" %} {{ document.title }} — {{ block.super }}{% endblock %}

{% block body %}
<div class="page-header">
  <h2 class="page-title">{% trans "Remove Document" %}</h2>
</div>
<div class="row">
  <div class="col-md-8">
    <p class="lead">
        {% blocktrans with document.title as document_title %}
          Are you sure you want to remove <a href="{{ document.get_absolute_url }}">{{ document_title }}</a>?
        {% endblocktrans %}
      </p>
    <form action="{% url "document_remove" document.id %}" method="POST">
      {% csrf_token %}
      <div class="form-actions">
        <input type="submit" value="{% trans "Yes, I am sure" %}" class="btn btn-danger" />
        <a href="{{ document.get_absolute_url }}" class="btn btn-default">{% trans "No, don't remove it" %}</a>
      </div>
    </form>
  </div>
</div>
{% endblock %}

lib/geonode/geonode/documents/templates/documents/document_upload.html
{% extends "documents/document_upload_base.html" %}
{% load bootstrap_tags %}
{% load i18n %}

{% block title %} {% trans "Upload Document" %} - {{ block.super }} {% endblock %}

{% block body_class %}documents upload{% endblock body_class %}

{% block head %}
    {% include "geonode/ext_header.html" %}
    {% include "geonode/app_header.html" %}
    {{ block.super }}
{% endblock %}

{% block body %}

<div class="col-md-8">
  <form id="upload_form"  method="post" enctype="multipart/form-data" action="{% url "document_upload" %}">
    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}" />
    {{ form.as_p }}
    <button type="submit" id="upload-button" class="btn btn-danger">Upload</button>
  </form>
</div>

{% endblock %}

{% block sidebar %}

<div class="col-md-4">
  <h3>{% trans "Permissions"  %}</h3>
  <form id="permission_form">
    {% include "_permissions.html" %}
  </form>
</div>

{% endblock %}

{% block extra_script %}
{% include "_permissions_form_js.html" %}

<script type="text/javascript">
    $('#id_doc_file').on('change', function(){
        if($('#id_title').val() == ''){
            $('#id_title').val($('#id_doc_file').val().replace("C:\\fakepath\\", ""));
        }
    });
    $("#resource").select2({
        minimumInputLength: 1,
        placeholder: 'Select layer, map or empty',
        width: 'element',
        ajax: {
          traditional: true,
          url: '{% url 'api_dispatch_list' api_name='api' resource_name='base' %}',
          data: function(term,page){
            return {
              type__in: ['layer','map'],
              title__contains: term.replace(/[`~!@#$%^&*()_|+\-=?;:'",.<>\{\}\[\]\\\/]/gi, '')
            }
          },
          results: function(data) {
            return {
              results: $.map(data.objects,function(object){
                return {id: object.id, text: object.title};
              })
            }
          }          
        }
      });
    $('#upload_form').submit(function(){
      $('#permissions').val(JSON.stringify(permissionsString($('#permission_form'),'base')));
    });
</script>
{% endblock extra_script %}