lib/geonode/rogue_geonode/geonode-master/geonode/layers/urls.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import patterns, url
from django.conf import settings
from django.views.generic import TemplateView

js_info_dict = {
    'packages': ('geonode.layers',),
}

urlpatterns = patterns(
    'geonode.layers.views',
    url(r'^$', TemplateView.as_view(template_name='layers/layer_list.html'), name='layer_browse'),
    url(r'^upload$', 'layer_upload', name='layer_upload'),
    url(r'^(?P<layername>[^/]*)$', 'layer_detail', name="layer_detail"),
    url(r'^(?P<layername>[^/]*)/metadata$', 'layer_metadata', name="layer_metadata"),
    url(r'^(?P<layername>[^/]*)/remove$', 'layer_remove', name="layer_remove"),
    url(r'^(?P<layername>[^/]*)/replace$', 'layer_replace', name="layer_replace"),
    url(r'^(?P<layername>[^/]*)/thumbnail$', 'layer_thumbnail', name='layer_thumbnail'),

    # url(r'^api/batch_permissions/?$', 'batch_permissions',
    #    name='batch_permssions'),
    # url(r'^api/batch_delete/?$', 'batch_delete', name='batch_delete'),
)

# -- Deprecated url routes for Geoserver authentication -- remove after GeoNode 2.1
# -- Use /gs/acls, gs/resolve_user/, gs/download instead
if 'geonode.geoserver' in settings.INSTALLED_APPS:
    urlpatterns = patterns('geonode.geoserver.views',
                           url(r'^acls/?$', 'layer_acls', name='layer_acls_dep'),
                           url(r'^resolve_user/?$', 'resolve_user', name='layer_resolve_user_dep'),
                           url(r'^download$', 'layer_batch_download', name='layer_batch_download_dep'),
                           ) + urlpatterns

lib/geonode/rogue_geonode/geonode-master/geonode/urls.py
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import include, patterns, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from geonode.sitemap import LayerSitemap, MapSitemap
from django.views.generic import TemplateView
from django.contrib import admin

import geonode.proxy.urls

from geonode.api.urls import api

import autocomplete_light

# Setup Django Admin
autocomplete_light.autodiscover()

admin.autodiscover()

js_info_dict = {
    'domain': 'djangojs',
    'packages': ('geonode',)
}

sitemaps = {
    "layer": LayerSitemap,
    "map": MapSitemap
}

urlpatterns = patterns('',

                       # Static pages
                       url(r'^/?$', TemplateView.as_view(template_name='index.html'), name='home'),
                       url(r'^help/$', TemplateView.as_view(template_name='help.html'), name='help'),
                       url(r'^developer/$', TemplateView.as_view(template_name='developer.html'), name='developer'),
                       url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),

                       # Layer views
                       (r'^layers/', include('geonode.layers.urls')),

                       # Map views
                       (r'^maps/', include('geonode.maps.urls')),

                       # Catalogue views
                       (r'^catalogue/', include('geonode.catalogue.urls')),

                       # data.json
                       url(r'^data.json$', 'geonode.catalogue.views.data_json', name='data_json'),

                       # Search views
                       url(r'^search/$', TemplateView.as_view(template_name='search/search.html'), name='search'),

                       # Social views
                       (r"^account/", include("account.urls")),
                       (r'^people/', include('geonode.people.urls')),
                       (r'^avatar/', include('avatar.urls')),
                       (r'^comments/', include('dialogos.urls')),
                       (r'^ratings/', include('agon_ratings.urls')),
                       (r'^activity/', include('actstream.urls')),
                       (r'^announcements/', include('announcements.urls')),
                       (r'^messages/', include('user_messages.urls')),
                       (r'^social/', include('geonode.social.urls')),
                       (r'^security/', include('geonode.security.urls')),

                       # Accounts
                       url(r'^account/ajax_login$', 'geonode.views.ajax_login', name='account_ajax_login'),
                       url(r'^account/ajax_lookup$', 'geonode.views.ajax_lookup', name='account_ajax_lookup'),

                       # Meta
                       url(r'^lang\.js$', TemplateView.as_view(template_name='lang.js', content_type='text/javascript'),
                           name='lang'),

                       url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict, name='jscat'),
                       url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps},
                           name='sitemap'),

                       (r'^i18n/', include('django.conf.urls.i18n')),
                       (r'^autocomplete/', include('autocomplete_light.urls')),
                       (r'^admin/', include(admin.site.urls)),
                       (r'^groups/', include('geonode.groups.urls')),
                       (r'^documents/', include('geonode.documents.urls')),
                       (r'^services/', include('geonode.services.urls')),
                       url(r'', include(api.urls)),
                       )

if "geonode.contrib.dynamic" in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            (r'^dynamic/', include('geonode.contrib.dynamic.urls')),
                            )

if 'geonode.geoserver' in settings.INSTALLED_APPS:
    # GeoServer Helper Views
    urlpatterns += patterns('',
                            # Upload views
                            (r'^upload/', include('geonode.upload.urls')),
                            (r'^gs/', include('geonode.geoserver.urls')),
                            )

if 'notification' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            (r'^notifications/', include('notification.urls')),
                            )

# Set up proxy
urlpatterns += geonode.proxy.urls.urlpatterns

# Serve static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler403 = 'geonode.views.err403'

# Featured Maps Pattens
urlpatterns += patterns('',
                        (r'^featured/(?P<site>[A-Za-z0-9_\-]+)/$', 'geonode.maps.views.featured_map'),
                        (r'^featured/(?P<site>[A-Za-z0-9_\-]+)/info$', 'geonode.maps.views.featured_map_info'),
                        )

lib/geonode/rogue_geonode/geoshape/urls.py
from django.conf.urls import patterns, include
from geonode.urls import urlpatterns as geonode_url_patterns
from maploom.geonode.urls import urlpatterns as maploom_urls
from tilebundler.api import TilesetResource
from fileservice.api import FileItemResource

tileset_resource = TilesetResource()
fileitem_resource = FileItemResource()

urlpatterns = patterns(
    '',
    (r'^gsschema/', include('gsschema.urls')),
    (r'^tileset/', include('tilebundler.urls', namespace='tilesets')),
    (r'^api/', include(tileset_resource.urls)),
    (r'^api/', include(fileitem_resource.urls)),
    (r'^proxy/', 'geoshape.views.proxy')
)

urlpatterns += geonode_url_patterns
urlpatterns += maploom_urls

lib/geonode/rogue_geonode/rogue_geonode-master/geoshape/urls.py
from django.conf.urls import patterns, include
from geonode.urls import urlpatterns as geonode_url_patterns
from maploom.geonode.urls import urlpatterns as maploom_urls
from tilebundler.api import TilesetResource
from fileservice.api import FileItemResource

tileset_resource = TilesetResource()
fileitem_resource = FileItemResource()

urlpatterns = patterns(
    '',
    (r'^gsschema/', include('gsschema.urls')),
    (r'^tileset/', include('tilebundler.urls', namespace='tilesets')),
    (r'^api/', include(tileset_resource.urls)),
    (r'^api/', include(fileitem_resource.urls)),
    (r'^proxy/', 'geoshape.views.proxy')
)

urlpatterns += geonode_url_patterns
urlpatterns += maploom_urls

lib/geonode/rogue_geonode/geonode-master/geonode/upload/forms.py
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################
import os
import files
import tempfile
from django import forms
from django.conf import settings
from django.core.exceptions import ValidationError
from geonode.layers.forms import JSONField
from geonode.upload.models import UploadFile
from geonode.geoserver.helpers import ogc_server_settings


class UploadFileForm(forms.ModelForm):

    class Meta:
        model = UploadFile


class LayerUploadForm(forms.Form):
    base_file = forms.FileField()
    dbf_file = forms.FileField(required=False)
    shx_file = forms.FileField(required=False)
    prj_file = forms.FileField(required=False)
    sld_file = forms.FileField(required=False)
    xml_file = forms.FileField(required=False)

    geogig = forms.BooleanField(required=False)
    geogig_store = forms.CharField(required=False)
    time = forms.BooleanField(required=False)

    abstract = forms.CharField(required=False)
    layer_title = forms.CharField(required=False)
    permissions = JSONField()

    spatial_files = (
        "base_file",
        "dbf_file",
        "shx_file",
        "prj_file",
        "sld_file",
        "xml_file")

    def clean(self):
        requires_datastore = () if ogc_server_settings.DATASTORE else (
            '.csv',
            '.kml')
        types = [t for t in files.types if t.code not in requires_datastore]

        def supported_type(ext):
            return any([t.matches(ext) for t in types])

        cleaned = super(LayerUploadForm, self).clean()
        base_name, base_ext = os.path.splitext(cleaned["base_file"].name)
        if base_ext.lower() == '.zip':
            # for now, no verification, but this could be unified
            pass
        elif not supported_type(base_ext.lower()[1:]):
            supported = " , ".join([t.name for t in types])
            raise forms.ValidationError(
                "%s files are supported. You uploaded a %s file" %
                (supported, base_ext))
        if base_ext.lower() == ".shp":
            dbf_file = cleaned["dbf_file"]
            shx_file = cleaned["shx_file"]
            if dbf_file is None or shx_file is None:
                raise forms.ValidationError(
                    "When uploading Shapefiles, .SHX and .DBF files are also required.")
            dbf_name, __ = os.path.splitext(dbf_file.name)
            shx_name, __ = os.path.splitext(shx_file.name)
            if dbf_name != base_name or shx_name != base_name:
                raise forms.ValidationError(
                    "It looks like you're uploading "
                    "components from different Shapefiles. Please "
                    "double-check your file selections.")
            if cleaned["prj_file"] is not None:
                prj_file = cleaned["prj_file"].name
                if os.path.splitext(prj_file)[0] != base_name:
                    raise forms.ValidationError(
                        "It looks like you're "
                        "uploading components from different Shapefiles. "
                        "Please double-check your file selections.")
        return cleaned

    def write_files(self):
        tempdir = tempfile.mkdtemp(dir=settings.FILE_UPLOAD_TEMP_DIR)
        for field in self.spatial_files:
            f = self.cleaned_data[field]
            if f is not None:
                path = os.path.join(tempdir, f.name)
                with open(path, 'wb') as writable:
                    for c in f.chunks():
                        writable.write(c)
        absolute_base_file = os.path.join(tempdir,
                                          self.cleaned_data["base_file"].name)
        return tempdir, absolute_base_file


class TimeForm(forms.Form):
    presentation_strategy = forms.CharField(required=False)
    precision_value = forms.IntegerField(required=False)
    precision_step = forms.ChoiceField(required=False, choices=[
        ('years',) * 2,
        ('months',) * 2,
        ('days',) * 2,
        ('hours',) * 2,
        ('minutes',) * 2,
        ('seconds',) * 2
    ])

    def __init__(self, *args, **kwargs):
        # have to remove these from kwargs or Form gets mad
        time_names = kwargs.pop('time_names', None)
        text_names = kwargs.pop('text_names', None)
        year_names = kwargs.pop('year_names', None)
        super(TimeForm, self).__init__(*args, **kwargs)
        self._build_choice('time_attribute', time_names)
        self._build_choice('end_time_attribute', time_names)
        self._build_choice('text_attribute', text_names)
        self._build_choice('end_text_attribute', text_names)
        widget = forms.TextInput(attrs={'placeholder': 'Custom Format'})
        if text_names:
            self.fields['text_attribute_format'] = forms.CharField(
                required=False, widget=widget)
            self.fields['end_text_attribute_format'] = forms.CharField(
                required=False, widget=widget)
        self._build_choice('year_attribute', year_names)
        self._build_choice('end_year_attribute', year_names)

    def _resolve_attribute_and_type(self, *name_and_types):
        return [(self.cleaned_data[n], t) for n, t in name_and_types
                if self.cleaned_data.get(n, None)]

    def _build_choice(self, att, names):
        if names:
            names.sort()
            choices = [('', '<None>')] + [(a, a) for a in names]
            self.fields[att] = forms.ChoiceField(
                choices=choices, required=False)

    def clean(self):
        starts = self._resolve_attribute_and_type(
            ('time_attribute', 'Date'),
            ('text_attribute', 'Text'),
            ('year_attribute', 'Number'),
        )
        if len(starts) > 1:
            raise ValidationError('multiple start attributes')
        ends = self._resolve_attribute_and_type(
            ('end_time_attribute', 'Date'),
            ('end_text_attribute', 'Text'),
            ('end_year_attribute', 'Number'),
        )
        if len(ends) > 1:
            raise ValidationError('multiple end attributes')
        if len(starts) > 0:
            self.cleaned_data['start_attribute'] = starts[0]
        if len(ends) > 0:
            self.cleaned_data['end_attribute'] = ends[0]
        return self.cleaned_data

    # @todo implement clean


class SRSForm(forms.Form):
    srs = forms.CharField(required=True)

lib/geonode/rogue_geonode/geonode-master/geonode/layers/templates/upload/layer_upload.html
{% extends "upload/layer_upload_base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block title %} {% trans "Upload Layer"  %} - {{ block.super }}  {% endblock %}

{% block body_class %}layers upload{% endblock %}


{% block head %}

{{ block.super }}
{% endblock %}

{% block body_outer %}
<div class="page-header">
  <a href="{% url "layer_browse" %}" class="btn btn-success pull-right">{% trans "Explore Layers" %}</a>
  <h2 class="page-title">{% trans "Upload Layers" %}</h2>
</div>
<div class="row">
  <div class="col-md-8">
    {% if incomplete %}
    <section class="widget" id="incomplete-download-list">
      <h3>{% trans "Incomplete Uploads" %}</h3>
      <p>{% trans "You have the following incomplete uploads" %}:</p>
      {% for u in incomplete %}
      <div class="clearfix uip" id="incomplete-{{ u.import_id }}">
        <div class="pull-left">{{ u.name }}, {% trans "last updated on" %} {{ u.date }}</div>
        <div class="upload_actions pull-right">
          <a class="btn btn-mini" href="#" id="resume-{{ u.import_id }}">{% trans "Resume" %}</a>
          <a class="btn btn-mini" href="#" id="delete-{{ u.import_id }}"><i class="icon-trash"></i> {% trans "Delete" %}</a>
        </div>
      </div>
      {% endfor %}
    </section>
    <div id="confirm-delete" class="hidden alert alert-warning">
      {% trans "Are you sure you want to delete this upload?" %}
      <a href="#y" class="btn btn-danger">{% trans "Delete" %}</a>
      <a href="#n" class="btn btn-default">{% trans "Cancel" %}</a>
      <a href="#yy">{% trans "Delete, and don't ask me again." %}</a>
    </div>
    {% endif %}

    {% block additional_info %}{% endblock %}

    {% if errors %}
    <div id="errors" class="alert alert-danger">
      {% for error in errors %}
      <p>{{ error }}</p>
      {% endfor %}
    </div>
    {% endif %}

    <div id="upload-status"></div>

    <section id="drop-zone">
      <h3><i class="fa fa-cloud-upload"></i><br />{% trans "Drop files here" %}</h3>
    </section>

    <p>{% trans " or select them one by one:" %}</p>

    <form id="file-uploader" method="post" enctype="multipart/form-data">
      <input class="btn" id="file-input" type="file" multiple>
    </form>

    <section class="widget">
      <ul id="global-errors"></ul>
      <h4>{% trans "Files to be uploaded" %}</h4>
      <div id="file-queue"></div>
    </section>

    <section class="charset">
      <p>{% trans "Select the charset or leave default" %}</p>
      <select id="charset">
        {% for charset in charsets %}
        {% if charset.0 == 'UTF-8' %} 
        <option selected='selected' value={{ charset.0 }}>{{ charset.1 }}</option>
        {% else %}
        <option value={{ charset.0 }}>{{ charset.1 }}</option>
        {% endif %}
        {% endfor %}
      </select>
    </section>
    
    <section>
      <a href="#" id="clear-button" class="btn btn-default">{% trans "Clear" %}</a>
      <a href="#" id="upload-button" class="btn btn-danger">{% trans "Upload files" %}</a>
    </section>
  </div>

  {% if GEONODE_SECURITY_ENABLED %}
  <div class="col-md-4">
    <h3>{% trans "Permissions"  %}</h3>
    <form id="permission_form">
      {% include "_permissions.html" %}
    </form>
  </div>
  {% endif %}
</div>
{% endblock %}


{% block extra_script %}
<script data-main="{% static 'geonode/js/upload/main' %}" 
  src="{% static 'lib/js/require.js' %}">
</script>
<script type="text/javascript" src="{% static 'geonode/js/upload/cookie.js' %}"></script>
<script type="text/javascript">
{% autoescape off %}

  csrf_token =  "{{ csrf_token }}",
  form_target = "{{ UPLOADER_URL }}",
  geogig_enabled = {{ GEOGIG_ENABLED|lower  }},
  time_enabled = {{ TIME_ENABLED|lower  }},
  userLookup = "{% url "geonode.views.ajax_lookup" %}"

{% endautoescape %}

</script>
{% if GEONODE_SECURITY_ENABLED %}
{% with resource=layer %}
{% include "_permissions_form_js.html" %}
{% endwith %}
{% endif %}
{% endblock extra_script %}

lib/geonode/rogue_geonode/geonode-master/geonode/layers/templates/upload/layer_upload_base.html
{% extends "site_base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %} {{ block.super }} {% endblock %}

{% block body_class %}data{% endblock %}

{% block body_outer %}
<div class="page-header">
  <a href="{% url "layer_browse" %}" class="btn btn-success pull-right">{% trans "Explore Layers" %}</a>
  <h2 class="page-title">{% trans "Upload Layers" %}</h2>
</div>
<div class="row">
  {% block body %}{% endblock body %}
  {% block sidebar %}{% endblock sidebar %}
</div>
{% endblock body_outer %}

lib/geonode/rogue_geonode/geonode-master/geonode/layers/templates/upload/layer_upload_crs.html
{% extends "upload/layer_upload_base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block body_class %}data data-list upload{% endblock %}

{% block title %} {% trans "Upload Layer" %} - {{ block.super }} {% endblock %}

{% block body %}
  <h2> {% trans "Provide CRS for " %} "{{ layer_name }}" </h2>

  <form method="POST" id="crsForm">
    {% csrf_token %}    
    <h3>{% trans "Coordinate Reference System" %}</h3>
    {% if native_crs %}
    <p>
    {% blocktrans %}
        A coordinate reference system for this layer could not be determined.
        Locate or enter the appropriate ESPG code for this layer below.
        One way to do this is do visit:
        <a href="http://prj2epsg.org/search" target="_">prj2epsg</a>
        and enter the following:
    {% endblocktrans %}
    </p>
    <pre>
    {{ native_crs }}
    </pre>
    <div>
        {{ form.srs.errors }}
        <label for="id_srs">EPSG Code (SRS)  :</label>{{ form.srs }}
    </div>
    <input id='next' type="button" value="{% trans "Next" %}"/>
    {% else %}
    <p>
        {% blocktrans %}
        There is a problem recognizing the projection of this data. Please
        reproject this data to a more common projection.
        {% endblocktrans %}
    </p>
    </p>
    {% endif %}
  </form>
<script data-main="{% static '/geonode/js/upload/srs' %}"
  src="{% static 'lib/js/require.js' %}">
</script>
{% endblock %}

lib/geonode/rogue_geonode/geonode-master/geonode/layers/templates/upload/layer_upload_csv.html
{% extends "upload/layer_upload_base.html" %}
{% load i18n %}
{% load static from staticfiles %}

{% block body_class %}data data-list upload{% endblock %}

{% block title %} {% trans "Upload Layer" %} - {{ block.super }} {% endblock %}

{% block body %}
{% if present_choices %}
<h2>{% trans "Geospatial Data" %}</h2>
<p>{% trans "Please indicate which attributes contain the latitude and longitude coordinates in the CSV data." %}</p>
{% if guessed_lat_or_lng %}
<p>{% blocktrans %}With this data, GeoNode was able to guess which attributes contain the
latitude and longitude coordinates, but please confirm that the correct
attributes are selected below.{% endblocktrans %}</p>
{% endif %}
<form method="POST" id="csvForm">
  {% csrf_token %}
  {% if error %}
  <div class="msg alert alert-error">{{ error }}</div>
  {% endif %}
  <div>
    <label for="lat" style="display: inline-block; width: 75px">{% trans "Latitude" %}</label>
    <select id="lat" name="lat">
      <option value="None">{% trans "Select an attribute" %}</option>
      {% for option in point_candidates %}
      <option value="{{ option }}"
      {% if selected_lat and selected_lat == option %}
      selected="selected"
      {% endif %}
      >{{ option }}</option>
      {% endfor %}
    </select>
  </div>
  <div style="margin: 10px 0">
    <label for="lat" style="display: inline-block; width: 75px">{% trans "Longitude" %}</label>
    <select id="lng" name="lng">
      <option value="None">{% trans "Select an attribute" %}</option>
      {% for option in point_candidates %}
      <option value="{{ option }}"
      {% if selected_lng and selected_lng == option %}
      selected="selected"
      {% endif %}
      >{{ option }}</option>
      {% endfor %}
    </select>
  </div>
  <a href="#" id="upload-csv-submit" class="btn">{% trans "Next" %}</a>
</form>
<div id="csv-status">
    <div id="status">

    </div>
</div>
{% else %}
<p>{% blocktrans %}We did not detect columns that could be used for the latitude and longitude.
Please verify that you have two columns in your csv file that can be used for
the latitude and longitude.{% endblocktrans %}</p>
{% endif %}
{% endblock %}

{% block extra_script %}
<script data-main="{% static 'geonode/js/upload/csv' %}"
  src="{% static 'lib/js/require.js' %}">
</script>
{% endblock %}

lib/geonode/rogue_geonode/geonode-master/geonode/layers/templates/upload/layer_upload_error.html
{% extends "upload/layer_upload_base.html" %}

{% block body_class %}data data-list upload{% endblock %}

{% block body %}
  <p>{{ error_msg|safe }}</p>
{% endblock %}

lib/geonode/rogue_geonode/geonode-master/geonode/layers/templates/upload/layer_upload_invalid.html
{% extends "upload/layer_upload_base.html" %}
{% load i18n %}
{% block body_class %}data data-list upload{% endblock %}

{% block body %}
<p>{% trans "Your upload is either complete or you haven't resumed an earlier one." %}</p>
<p>{% trans "Return to" %} <a href="{% url "layer_upload" %}">{% trans "Upload Form" %}</a>.</p>
{% endblock %}

lib/geonode/rogue_geonode/geonode-master/geonode/layers/templates/upload/no_upload.html
{% extends "upload/base.html" %}
{% load i18n %}

{% block body %}
<div class="twocol">
    <p>{% trans "Your upload is either complete or you haven't resumed an earlier one." %}</p>
    <p>{% blocktrans %}Returning to the upload starting page in <span id="cnt">5</span>seconds {% endblocktrans %}.</p>
    <p>{% blocktrans %} Or just go {% endblocktrans %}<a href="{% url "layer_upload" %}">{% blocktrans %}now{% endblocktrans %}</a>.</p>
</div>
<script type="text/javascript">
    var cnt = 5;
    window.setInterval(function() {
        Ext.get('cnt').dom.innerHTML = cnt--;
        if (cnt == 0) {
            window.location = "{% url "layer_upload" %}";
        }
    }, 1000);
</script>
{% endblock %}